# Generated by Django 2.1.2 on 2018-10-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('money', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tax_reg_no', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('unit_price', models.IntegerField()),
                ('score', models.IntegerField()),
                ('status', models.IntegerField()),
                ('status_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(max_length=255)),
                ('discount_price', models.CharField(max_length=255)),
                ('hospital_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('banner_image', models.CharField(max_length=255)),
                ('detail_image', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('side_effect', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('view_count', models.PositiveIntegerField()),
                ('first_lived_at', models.DateTimeField(blank=True, null=True)),
                ('last_lived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
    ]
